-- Instagram Comments Table
-- Stores comments with support for nested replies (self-referencing)

CREATE TABLE IF NOT EXISTS instagram_comments (
  -- IDs
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instagram_comment_id TEXT UNIQUE NOT NULL,  -- The "id" from JSON (e.g., "17899746144315959")
  
  -- RELATIONSHIPS
  reel_shortcode TEXT NOT NULL REFERENCES raw_instagram_reels(shortcode) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES instagram_comments(id) ON DELETE CASCADE, -- SELF REFERENCE for nested replies
  
  -- CONTENT
  text_content TEXT,
  owner_username TEXT,
  
  -- METADATA
  like_count INT DEFAULT 0,
  posted_at TIMESTAMPTZ,
  
  -- SYSTEM
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_comments_reel_shortcode ON instagram_comments(reel_shortcode);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON instagram_comments(parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_comments_owner_username ON instagram_comments(owner_username);
CREATE INDEX IF NOT EXISTS idx_comments_posted_at ON instagram_comments(posted_at DESC);

-- Index for finding top-level comments (no parent)
CREATE INDEX IF NOT EXISTS idx_comments_top_level ON instagram_comments(reel_shortcode) 
  WHERE parent_comment_id IS NULL;

-- -- Enable Row Level Security (optional but recommended)
-- ALTER TABLE instagram_comments ENABLE ROW LEVEL SECURITY;

-- -- Example policy: Allow all operations for authenticated users
-- CREATE POLICY IF NOT EXISTS "Allow all for authenticated users" 
--   ON instagram_comments 
--   FOR ALL 
--   TO authenticated 
--   USING (true);

