-- 1. Enable the Vector extension (v0.7.0+ supports BIT types)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create the Video Frames Table
CREATE TABLE IF NOT EXISTS video_frames (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- RELATIONSHIPS (Ensure raw_instagram_reels table exists first)
  reel_shortcode TEXT NOT NULL REFERENCES raw_instagram_reels(shortcode) ON DELETE CASCADE,
  
  -- FRAME DATA
  timestamp_seconds REAL NOT NULL,        -- Position in video (e.g., 2.0, 4.0)
  phash BIT(64) NOT NULL,                 -- 64-bit perceptual hash
  
  -- SYSTEM
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. High-Performance Indexing
-- Standard index for lookups by Reel
CREATE INDEX IF NOT EXISTS idx_frames_reel_shortcode ON video_frames(reel_shortcode);

-- HNSW Index for Hamming Distance similarity search
-- bit_hamming_ops is the specific operator class for BIT types
CREATE INDEX IF NOT EXISTS idx_frames_phash_hnsw ON video_frames 
USING hnsw (phash bit_hamming_ops);

-- 4. Create a Search Function (Stored Procedure)
-- This allows you to call 'find_similar_videos' via Supabase RPC
CREATE OR REPLACE FUNCTION find_similar_videos(
    query_hash BIT(64), 
    max_distance INT DEFAULT 5, 
    match_limit INT DEFAULT 10
)
RETURNS TABLE (
    reel_shortcode TEXT,
    timestamp_seconds REAL,
    hamming_distance INT
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        vf.reel_shortcode,
        vf.timestamp_seconds,
        (vf.phash <~> query_hash)::INT as hamming_distance -- <~> is the Hamming distance operator
    FROM video_frames vf
    WHERE (vf.phash <~> query_hash) < max_distance
    ORDER BY vf.phash <~> query_hash ASC
    LIMIT match_limit;
END;
$$;

-- 5. Documentation
COMMENT ON TABLE video_frames IS 'Stores pHashes of video frames for duplicate/repost detection';
COMMENT ON INDEX idx_frames_phash_hnsw IS 'HNSW index for fast Hamming distance searches on 64-bit hashes';