-- Pipeline run audit log
-- One row per pipeline invocation. Inserted as "running" on entry,
-- updated with the final outcome on exit (even on crash the row remains
-- with status="running" as evidence of an incomplete run).

CREATE TABLE IF NOT EXISTS pipeline_runs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shortcode     TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'running',  -- running | success | already_processed | repost | filtered | error

  -- timing
  triggered_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ,
  duration_ms   INT,

  -- repost fields
  original_shortcode  TEXT,
  similarity          FLOAT,

  -- filtered fields
  sentiment_label       TEXT,
  sentiment_explanation TEXT,

  -- success fields
  danger_score        INT,
  crimes_count        INT,
  recommended_action  TEXT,

  -- error fields
  error_reason  TEXT
);

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_shortcode   ON pipeline_runs(shortcode);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status      ON pipeline_runs(status);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_triggered   ON pipeline_runs(triggered_at DESC);
