-- Failed requests queue
-- Written to only when all retry attempts are exhausted.
-- Use this table to manually requeue shortcodes for reprocessing.

CREATE TABLE IF NOT EXISTS failed_requests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shortcode     TEXT        NOT NULL,
  failed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_error    TEXT,
  step_failed   TEXT,       -- e.g. "step_5_upload"
  attempts      INT         NOT NULL DEFAULT 3,
  resolved      BOOLEAN     NOT NULL DEFAULT FALSE  -- mark TRUE after manual reprocessing
);

CREATE INDEX IF NOT EXISTS idx_failed_requests_shortcode ON failed_requests(shortcode);
CREATE INDEX IF NOT EXISTS idx_failed_requests_resolved  ON failed_requests(resolved) WHERE resolved = FALSE;

-- Add unique constraint on video_frames(reel_shortcode, timestamp_seconds)
-- so retried fingerprint saves use ON CONFLICT DO NOTHING instead of failing.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_video_frames_reel_timestamp'
  ) THEN
    ALTER TABLE video_frames
      ADD CONSTRAINT uq_video_frames_reel_timestamp
      UNIQUE (reel_shortcode, timestamp_seconds);
  END IF;
END;
$$;
