-- Processed Crime Reports Table
-- Stores the final crime analysis report from the media processing pipeline.
-- This is the output of step 7 (media analysis) for dashboard consumption.

CREATE TABLE IF NOT EXISTS processed_crime_reports (
    -- PRIMARY KEY
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- FOREIGN KEY REFERENCE
    -- Links to the original Instagram reel
    reel_shortcode TEXT NOT NULL REFERENCES raw_instagram_reels(shortcode) ON DELETE CASCADE,
    
    -- PROMOTED METRICS (Optimized for fast indexing & filtering in dashboard)
    approximate_location TEXT,     -- e.g., 'Giza, Saft El Laban, Saft Axis'
    rule_violated TEXT,            -- e.g., 'Reckless driving / Endangering public safety'
    severity TEXT,                 -- e.g., 'minor', 'moderate', 'severe', 'critical'
    danger_score INT,              -- Numeric score (1-10) for sorting by danger level
    
    -- DESCRIPTIVE TEXT
    overall_assessment TEXT,       -- The summary of the whole incident (from MediaAnalysisResult)
    recommended_action TEXT,       -- Action recommendation based on analysis
    
    -- THE "JSON DUMP"
    -- Contains full video_analysis, audio_analysis, and extra metadata
    -- Stores the complete MediaAnalysisResult for detailed view
    raw_analysis_data JSONB NOT NULL,
    
    -- SYSTEM METRICS
    processed_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES: Crucial for a dashboard with thousands of entries
-- Index on location for geographic filtering
CREATE INDEX IF NOT EXISTS idx_reports_location ON processed_crime_reports(approximate_location);

-- Index on severity for filtering by danger level
CREATE INDEX IF NOT EXISTS idx_reports_severity ON processed_crime_reports(severity);

-- Index on shortcode for lookup and foreign key performance
CREATE INDEX IF NOT EXISTS idx_reports_shortcode ON processed_crime_reports(reel_shortcode);

-- Index on danger_score for sorting
CREATE INDEX IF NOT EXISTS idx_reports_danger_score ON processed_crime_reports(danger_score DESC);

-- Index on processed_at for time-based queries
CREATE INDEX IF NOT EXISTS idx_reports_processed_at ON processed_crime_reports(processed_at DESC);

-- Composite index for common dashboard queries (severity + danger_score + time)
CREATE INDEX IF NOT EXISTS idx_reports_dashboard ON processed_crime_reports(severity, danger_score DESC, processed_at DESC);

-- Unique constraint to ensure one report per reel (required for upsert functionality)
-- This enables the crud.py upsert operation to update existing reports on reprocessing
ALTER TABLE processed_crime_reports 
  DROP CONSTRAINT IF EXISTS uq_reports_reel_shortcode;

ALTER TABLE processed_crime_reports 
  ADD CONSTRAINT uq_reports_reel_shortcode UNIQUE (reel_shortcode);

