-- Penal Code Embeddings Table
-- Stores Egyptian penal code articles with vector embeddings for semantic search
-- Uses pgvector extension for efficient similarity search on embeddings

-- Enable pgvector extension (required for vector similarity search)
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the penal_code_embeddings table
CREATE TABLE IF NOT EXISTS penal_code_embeddings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_number TEXT NOT NULL,       -- e.g., "86"  (modifier like "مكرر" is part of article_text)
    book_title     TEXT NOT NULL,       -- e.g., "الكتاب الثاني"
    book_description TEXT,             -- e.g., "الجنايات والجنح..."
    chapter_title  TEXT NOT NULL,       -- e.g., "الباب الثاني: الجنايات والجنح..."
    article_text   TEXT NOT NULL,       -- Full text of the article
    combined_text  TEXT NOT NULL,       -- "{chapter_title} | {article_text}" — used to generate the embedding
    embedding      vector(3072) NOT NULL -- OpenAI text-embedding-3-large produces 3072-dim vectors
);

-- GIN index for full-text search — 'simple' config works for Arabic
-- ('arabic' dictionary is not bundled with Postgres by default)
CREATE INDEX IF NOT EXISTS idx_penal_code_fts
    ON penal_code_embeddings USING GIN (to_tsvector('simple', article_text));

-- Note: HNSW/IVFFlat indexes are limited to 2000 dimensions; pgvector uses
-- an exact sequential scan for 3072-dim vectors, which is fast enough for
-- a small article count (< 10 000 rows) and gives perfect recall.

-- ─────────────────────────────────────────────
-- RPC function: semantic vector search
-- Called via supabase.rpc('match_penal_code', {...})
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION match_penal_code(
    query_embedding vector(3072),
    match_threshold float DEFAULT 0.3,
    match_count     int   DEFAULT 10
)
RETURNS TABLE (
    id               bigint,
    article_number   text,
    book_title       text,
    book_description text,
    chapter_title    text,
    article_text     text,
    similarity       float
)
LANGUAGE sql STABLE
SECURITY DEFINER                          -- runs as the function owner, bypasses RLS
SET search_path = public
AS $$
    SELECT
        id,
        article_number,
        book_title,
        book_description,
        chapter_title,
        article_text,
        (1 - (embedding <=> query_embedding))::float AS similarity
    FROM penal_code_embeddings
    WHERE 1 - (embedding <=> query_embedding) > match_threshold
    ORDER BY embedding <=> query_embedding
    LIMIT match_count;
$$;

-- Allow PostgREST (anon + authenticated roles) to call this function
GRANT EXECUTE ON FUNCTION match_penal_code(vector, float, int)
    TO anon, authenticated, service_role;
