-- Instagram Reels Table
-- Stores raw Instagram reel data with metadata and engagement stats

CREATE TABLE IF NOT EXISTS raw_instagram_reels (
  -- IDENTIFIERS
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instagram_id TEXT UNIQUE NOT NULL,      -- From JSON: "id" (e.g., "3768188262447963126")
  shortcode TEXT UNIQUE NOT NULL,         -- From JSON: "shortCode" (e.g., "DRLS0KOAdv2")
  
  -- CONTENT & CONTEXT
  caption TEXT,                           -- From JSON: "caption"
  owner_id TEXT,                          -- From JSON: "ownerId"
  owner_username TEXT,                    -- From JSON: "ownerUsername"
  posted_at TIMESTAMPTZ,                  -- From JSON: "timestamp"
 
  -- ENGAGEMENT SNAPSHOT (At time of scrape)
  -- Stores: video_view_count, video_play_count, likes_count, comments_count, video_duration
  stats JSONB,                            
  
  -- STORAGE REFERENCES (Permanent)
  storage_bucket_path TEXT,               -- Path in Supabase Storage (e.g., "DRLS0KOAdv2.mp4")
  
  -- SYSTEM
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_reels_shortcode ON raw_instagram_reels(shortcode);
CREATE INDEX IF NOT EXISTS idx_reels_owner_username ON raw_instagram_reels(owner_username);
CREATE INDEX IF NOT EXISTS idx_reels_posted_at ON raw_instagram_reels(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_reels_created_at ON raw_instagram_reels(created_at DESC);

-- -- Enable Row Level Security (optional but recommended)
-- ALTER TABLE raw_instagram_reels ENABLE ROW LEVEL SECURITY;

-- -- Example policy: Allow all operations for authenticated users
-- CREATE POLICY IF NOT EXISTS "Allow all for authenticated users" 
--   ON raw_instagram_reels 
--   FOR ALL 
--   TO authenticated 
--   USING (true);

